# stage1 : build
FROM node:18-alpine3.17 AS build

# workdir
WORKDIR /app

# dep install
# COPY ../../../package*.json ./
COPY package*.json ./
RUN npm ci

# dep copy
COPY . .

# build
RUN npm run auth:build

# remove dev dep
RUN npm prune --production

# stage2 : create production image
FROM node:18-alpine3.15

# workdir
WORKDIR /app

# copy for prod
COPY --from=build /app/dist/backend/apps/shuttle-auth-server/main.js /app
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package*.json ./

# expose port
EXPOSE 3000

# start app
CMD ["node", "main"]